<?php


/**
 * This class defines the structure of the 'trip' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/20/13 17:54:44
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class TripTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.TripTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('trip');
		$this->setPhpName('Trip');
		$this->setClassname('Trip');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('ROUTE_ID', 'RouteId', 'INTEGER', 'route', 'ID', true, null, null);
		$this->addForeignKey('DRIVER_VEHICLE_ID', 'DriverVehicleId', 'INTEGER', 'driver_vehicle', 'ID', true, null, null);
		$this->addColumn('PRICE', 'Price', 'FLOAT', true, null, null);
		$this->addColumn('TRIP_TIME', 'TripTime', 'INTEGER', true, null, null);
		$this->addColumn('TRIP_START', 'TripStart', 'TIMESTAMP', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Route', 'Route', RelationMap::MANY_TO_ONE, array('route_id' => 'id', ), null, null);
    $this->addRelation('DriverVehicle', 'DriverVehicle', RelationMap::MANY_TO_ONE, array('driver_vehicle_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', ),
		);
	} // getBehaviors()

} // TripTableMap
