<?php


/**
 * Skeleton subclass for performing query and update operations on the 'vehicle' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 10/20/13 17:54:43
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VehiclePeer extends BaseVehiclePeer {

} // VehiclePeer
