<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/21 00:20:07
sfConfig::add(array(
  'mod_driver_vehicle_enabled' => true,
  'mod_driver_vehicle_view_class' => 'sfPHP',
));
